services:
  ems-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ems-front-app
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - ems-network

networks:
  ems-network:
    driver: bridge
